### ISSUE TITLE
Wrong exit code returned while trying to stop the server

### ISSUE THREAD

**Issue by QuasiQA** [kawansoft/aceql-http#1]
AceQL command `aceql-server -stop` returns error while successfully stop the server. 
It becomes a problem when trying to use AceQL in my pipeline on Jenkins since Jenkins treat this as an error in the build. Despite workaround exist, I would like to fix the root-cause of such behavior.

The reason is that wrong exit code thrown by the AceQL server for handling `-stop` option: 
https://github.com/kawansoft/aceql-http/blob/c0729c55d1f5905a1769508827c7abc73af6f10d/src/main/java/org/kawanfw/sql/WebServer.java#L305

What I suggest is to throw 0 code since server stopped successfully,
so the fix is as easy as change return code:
`System.exit(0);`

**Comment by ndepomereu** [comment]
Yes, I will generate new version asap (next 48 hours) with `System.exit(0);`
Regards,
Nicolas

**Comment by ndepomereu** [comment]
New version 3.2.1 that now returns `System.exit(0); `on server stop is online (www.aceql.com).

**Comment by QuasiQA** [comment]
Thank you, Nicolas
I've tested, that helped with an issue
