### ISSUE TITLE
Failed to create work directory - Embedded Tomcat cannot start

### ISSUE THREAD

**Issue by ThomasSchoenbeck** [kawansoft/aceql-http#2]
After aceql established the database connection it tries to create a folder for the embedded tomcat. that doesn't work but so far i have not figured out why.

It seems it uses and ENV to determine where to create that new directory, but i can't find any information inside the documentation which ENV is required.

Error message:
```java
WARNING: Failed to create work directory [/?/.kawansoft/tomcat-embedded-temp/work/Tomcat/localhost/ROOT] for context []
Oct 31, 2019 4:46:06 PM org.apache.catalina.core.ContainerBase startInternal
SEVERE: A child container failed during start
```

currently i have set these ENV
- ACEQL_HOME
- JAVA_HOME
- CLASSPATH
- TMPROOT

any idea?

**Comment by QuasiQA** [comment]
Hello Thomas,
Are you running aceql on linux?
I guess it may be caused by running aceql under non-root user

**Comment by ThomasSchoenbeck** [comment]
Hi. Yes the docker image runs as non-root. As you stated, i had not setup the user home dir correctly.
