### ISSUE TITLE
Vulnerability Pull Requests

### ISSUE THREAD

**Issue by granadacoder** [kawansoft/aceql-http#33]
Hi.

Is this repo abandoned?

There are 2 dependapot pull requests.

And I did a PR to deal with vulnerability version uplifts and to fix the breaking changed due to javax/Jakarta issues.

Thank you for any update.

**Comment by ndepomereu** [comment]
Hi granadacoder 

Thank you for your valuable contributions! I've merged your PR addressing the vulnerabilities and javax/Jakarta issues. Our software is *actively* maintained, and these updates will be included in the next release soon.

Thanks again for your support!

Best,
Nicolas

**Comment by granadacoder** [comment]
Thank you.

**Comment by granadacoder** [comment]
I appreciate your efforts to get a build out soon.

Unbuilt code is nice, but built code is better. :)
