### ISSUE TITLE
cannot change port 

### ISSUE THREAD

**Issue by quirrel1002** [kawansoft/aceql-http#5]
Hello,
hopefully this can be answered quickly, I have tried to use the aceql on linux, and when I start it with cmdLine:
`aceql-server -start -host=localhost –port 8080`
I get the follwing ouput:
`[ACEQL HTTP START] AceQL HTTP Web Server OK. Running on port 9090`

I cannot find any hint in output that anyhting is wrong

I used Version AceQL HTTP Community v4.1 - 13-Feb-2020

regards
Tobias

**Comment by QuasiQA** [comment]
Try to be consistent in parameters usage and follow readme examples:
`aceql-server -start -host localhost –port 8080` instead of `aceql-server -start -host=localhost –port 8080`
It worked for me

**Comment by quirrel1002** [comment]
sorry for different syntax, actually I trie actually both...
`aceql-server -start -host localhost –port 8080`
and 
`aceql-server -start -host=localhost –port 8080`
but the result was the same

**Comment by QuasiQA** [comment]
I have no other suggestions but maybe port 8080 is occupied by some other app?

**Comment by ndepomereu** [comment]
No, the reason is that the minus sign on port is not the regular awaited standard minus sign, don't know how that can happens, I had already this problem some time ago.
You can see that if you" zoom" or "loop" on the line.
Rewrite the start line by suppressing the port minus sign and use the one of localhost or start-server.

**Comment by quirrel1002** [comment]
thanks Nicolas, you are right on the '-' it was somehow was not correct one, after rewrite it was ok. It may copy from web site somehow was not working as expected ...
so can be closed

**Comment by ndepomereu** [comment]
Welcome!
